version: '3.1'

services:
    prometheus:
            image: prom/prometheus:latest
            container_name: gputoolkit_prometheus
            volumes:
              - ./prometheus/:/etc/prometheus/
              - prometheus_data:/prometheus
            command:
              - '--config.file=/etc/prometheus/prometheus.yml'
              - '--storage.tsdb.path=/prometheus'
              - '--web.console.libraries=/etc/prometheus/console_libraries'
              - '--web.console.templates=/etc/prometheus/consoles'
              - '--storage.tsdb.retention=200h'
              - '--web.enable-lifecycle'
            restart: always
            expose:
              - 9090
            networks:
              - monitor-net
            ports:
              - 9090:9090
    grafana:
            image: grafana/grafana:5.2.2
            container_name: gputoolkit_grafana
            depends_on:
                - prometheus
            expose:
                - 3000
            ports:
              - 3000:3000
            volumes:
              - grafana_data:/var/lib/grafana
              - ./grafana/provisioning/:/etc/grafana/provisioning/
#            env_file:
#             - ./grafana/config.monitoring
            networks:
              - monitor-net
            restart: always

volumes:
    grafana_data: {}
    prometheus_data: {}

networks:
    monitor-net:
        driver: bridge
   
 #   grafana:
 #           image: grafana/grafana:5.2.2
 #           container_name: grafana
 #           volumes:
 #             - grafana_data:/var/lib/grafana
 #             - ./grafana/datasources:/etc/grafana/datasources
 #             - ./grafana/dashboards:/etc/grafana/dashboards
 #             - ./grafana/setup.sh:/setup.sh
 #           entrypoint: /setup.sh
 #          environment:
 #            - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
 #            - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
 #            - GF_USERS_ALLOW_SIGN_UP=false
 #          restart: unless-stopped
 #          expose:
 #            - 3000
 #          networks:
 #            - monitor-net
 #          ports:
 #            - 3000:3000

