{
 "title": "gpu_toolkit",
 "description": "list all of the the map relationships between gpu and attached vgpu, the value is the Vgpu ID",
 "time": { "from": "2018-08-20T14:55:07.951Z", "to": "2018-08-22T14:55:07.951Z" },
 "panels": [
  {
   "title": "VGPUs",
   "type": "singlestat",
   "description": "the total number of VGPUs",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(gputoolkit_attached_vgpu)"
    }
   ]
  },
  {
   "title": "Nvidia driver",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gputoolkit_nvdriver_version" }
   ]
  },
  {
   "title": "GPUs average utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization) / count(dcgm_gpu_utilization)"
    }
   ]
  },
  {
   "title": "GPUs average power usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dcgm_power_usage) / count(dcgm_power_usage) "
    }
   ]
  },
  {
   "title": "GPU0 Current ECC status",
   "type": "singlestat",
   "description": "return the the status of ECC Enable/Disable",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg"
  },
  {
   "title": "GPU2 Current ECC status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "gputoolkit_current_ecc_flag{gpu=\"2\"}"
    }
   ]
  },
  {
   "title": "GPUs",
   "type": "singlestat",
   "description": "shows the total number of attached GPUs.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gputoolkit_device_num" }
   ]
  },
  {
   "title": "GPU3 Current ECC status",
   "type": "singlestat",
   "description": "return the the status of ECC Enable/Disable",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "gputoolkit_current_ecc_flag{gpu=\"2\"}"
    }
   ]
  },
  {
   "title": "GPU3 Current ECC status",
   "type": "singlestat",
   "description": "return the the status of ECC Enable/Disable",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "gputoolkit_current_ecc_flag{gpu=\"3\"}"
    }
   ]
  },
  {
   "title": "vGPU info",
   "type": "table",
   "description": "merge all vGPU info in this table, such as vGPU type, license, ID etc.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "gputoolkit_vgpu_license" },
    { "expr": "gputoolkit_vgpu_type" },
    { "expr": "gputoolkit_attached_vgpu" }
   ]
  },
  {
   "title": "Fan speed",
   "type": "graph",
   "description": "Fan speed for each GPU",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "gputoolkit_fan_speed" }
   ]
  },
  {
   "title": "GPUs temperature",
   "type": "graph",
   "description": "describe the temperature for each GPU",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "dcgm_gpu_temp" }
   ]
  }
 ]
}